Numpy is the fundamental package for scientific computing in python
Its provide multidimensional array object
Numpy arrays have a fixed size at creation
Its provide efficient storage
It is also provide better ways of handling data for processing
It is fast 
It is easy to learn
Numpy uses relatively less memory to store data.


In [2]:
#import numpy
import numpy 


In [4]:
# check the version of numpy
numpy.__version__

'1.21.5'

In [5]:
# lets create a numpy array
numpy.array([1,2,3])

array([1, 2, 3])

In [7]:
# make it simple: use module aliasing
import numpy as np
a = np.array([10,20,30])
a

array([10, 20, 30])

In [8]:
l = [10,20,30]
l

[10, 20, 30]

In [9]:
l*3    # l is list: it will perform repettion

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [10]:
a*3      # a is numpy array:  it will perform elementwise multiplication

array([30, 60, 90])

In [11]:
a

array([10, 20, 30])

In [12]:
l

[10, 20, 30]

In [13]:
# check size of l and a
print('Array size:', a.__sizeof__())
print('List size:', l.__sizeof__())

Array size: 116
List size: 104


In [14]:
l*3*2

[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]

In [15]:
a*3*2

array([ 60, 120, 180])

In [18]:
for i in range(100):
    print(a*100)

[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 3000]
[1000 2000 300

In [20]:
for i in range(100):
    print(l)

[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]
[10, 20, 30]

In [21]:
a.dtype

dtype('int32')

In [22]:
# we can assign 8 bit, 32 bit, 64 bit dtype
myarr = np.array([1,2,3,32,64],np.int8)

In [23]:
myarr

array([ 1,  2,  3, 32, 64], dtype=int8)

In [25]:
myarr1 = np.array([1,2,32,45,3777899],np.int8)
myarr1

array([  1,   2,  32,  45, 107], dtype=int8)

In [26]:
# suppose we are using int8 then will take care of in list number is not bigger than int8
myarr

array([ 1,  2,  3, 32, 64], dtype=int8)

In [27]:
myarr[3]  # to access element in this array

32

In [28]:
# create 1D array
a = np.array([11,22,33,44])

In [29]:
a

array([11, 22, 33, 44])

In [30]:
a.ndim

1

In [31]:
# Create 2D array
a2 = np.array([[1,2],[3,4],[5,6]])
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
a2.ndim

2

In [33]:
a2.shape

(3, 2)

In [42]:
# Create 3D array: is made up of 2D array
a3 = np.array([[[1,2,100],[3,4,100],[11,12,111],[100,200,101]],[[5,6,1112],[7,8,1234],[33,44,2233],[111,222,44]]])
a3

array([[[   1,    2,  100],
        [   3,    4,  100],
        [  11,   12,  111],
        [ 100,  200,  101]],

       [[   5,    6, 1112],
        [   7,    8, 1234],
        [  33,   44, 2233],
        [ 111,  222,   44]]])

In [43]:
a3.ndim

3

In [44]:
a3.shape

(2, 4, 3)

In [45]:
type(a3)

numpy.ndarray

In [47]:
a4 = np.array([1,2,3,'abc'])
# if we give str or hetro data then its data type is unicode

In [48]:
a4

array(['1', '2', '3', 'abc'], dtype='<U11')

In [49]:
a4.dtype

dtype('<U11')

In [50]:
# Features of Numpy
# 1. Sequence order is preserved
# 2. indexing supported
# 3. slicing is supported
# 4. homo., hetro. value accepted

In [53]:
# other options for creating a numpy array
# arange of numpy is same as that of range in python
np.arange(5)

array([0, 1, 2, 3, 4])

In [54]:
np.arange(101,111)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [57]:
np.arange(100,0,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [58]:
# odd numbers
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [61]:
# Create an array with all ones
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [63]:
np.ones(10).ndim

1

In [66]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
np.ones((5,5)).ndim

2

In [68]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [69]:
np.ones((3,2,3)).ndim

3

In [71]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])